spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/myshift
    username: postgres
    password:
server:
    port: 8080

demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://localhost
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus