spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myshift
    username: postgres
    password:
server:
    port: 8080
    tomcat:
       access-log-enabled: true
       access-log-renameOnRotate: true
       access-log-buffered: false
       basedir: .

demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://localhost
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus